using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Design", "CA1054:URI-like parameters should not be strings", Justification = "Intentionally strings")]
[assembly: SuppressMessage("Design", "CA1056:URI-like properties should not be strings", Justification = "Intentionally string.")]
[assembly: SuppressMessage("Globalization", "CA1308:Normalize strings to uppercase", Justification = "Some strings are stored in lowercase.")]
[assembly: SuppressMessage("Maintainability", "CA1515:Consider making public types internal", Justification = "SignalR requires public types at runtime")]
[assembly: SuppressMessage("Performance", "CA1852:Seal internal types", Justification = "Not a library project.")]
[assembly: SuppressMessage("Performance", "CA1861:Avoid constant arrays as arguments", Justification = "Readability")]
[assembly: SuppressMessage("Reliability", "CA2007:Consider calling ConfigureAwait on the awaited task", Justification = "Not needed in an ASP.NET Core project.")]
[assembly: SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Used in DTO classes.")]
[assembly: SuppressMessage("Usage", "CA2234:Pass system uri objects instead of strings", Justification = "HttpClient uses partial path")]
[assembly: SuppressMessage("Security", "CA5394:Do not use insecure randomness", Justification = "Secure randomness not needed")]
[assembly: SuppressMessage("Style", "IDE0046:Convert to conditional expression", Justification = "Readability")]
[assembly: SuppressMessage("Style", "IDE0058:Expression value is never used", Justification = "Expression values not required")]
[assembly: SuppressMessage("Style", "IDE0305:Simplify collection initialization", Justification = "Readability")]